common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host:  <%= ENV['MYSQL_HOST'] %>
  username:  <%= ENV['MYSQL_USERNAME'] %>
  password:  <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *common
  database: codem_schedule_development

test: &test
  <<: *common
  database: codem_schedule_test

production:
  <<: *common
  database: codem
