common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: db
  username: codem
  password: codem

development:
  <<: *common
  database: codem_schedule_development

test: &test
  <<: *common
  database: codem_schedule_test

production:
  <<: *common
  database: codem
